server {
  listen 80;
  server_name localhost;

  location /test-app/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /index.html;
  }

  location = /test-app {
    return 301 /test-app/;
  }

  location = / {
    return 301 /test-app/;
  }
}