server {
    listen 80;
    server_name localhost;

    location /hello-squad/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ =404;

        location ~* \.(css|js)$ {
            expires 30d;
            add_header Cache-Control "public";
        }
    }

    location /hello-squad {
        return 301 /hello-squad/;
    }

    error_page 500 502 503 504 /50x.html;
    error_page 404 /404.html;

    location = /50x.html {
        internal;
    }

    location = /404.html {
        internal;
    }
}