# SquadOps Framework Version Management
# This file is the single source of truth for the SquadOps framework version
#
# ⚠️  DO NOT EDIT THIS FILE DIRECTLY
# Use scripts/maintainer/version_cli.py for all version management:
#   python scripts/maintainer/version_cli.py bump <version> [notes]
#   python scripts/maintainer/version_cli.py update <agent> <version> [notes]

# Framework Version
SQUADOPS_VERSION = "0.6.5"

# Agent Versions (individual agent versions)
AGENT_VERSIONS = {
    "max": "0.6.5",  # Real agent with local LLM
    "neo": "0.6.5",  # Real agent with file modification capabilities
    "nat": "0.6.5",  # Mock agent
    "joi": "0.0.0",  # Mock agent
    "data": "0.0.0", # Mock agent
    "eve": "0.6.5",  # Mock agent
    "quark": "0.0.0", # Mock agent
    "og": "0.0.0",   # Mock agent
    "glyph": "0.0.0", # Mock agent
    "hal": "0.0.0"   # Mock agent
}

# Configuration Versions
CONFIG_VERSIONS = {
    "max": {"llm": "llama3.1:8b", "config": "lead-agent"},
    "neo": {"llm": "qwen2.5:7b", "config": "dev-agent"},
    "nat": {"llm": "mock", "config": "strategy-agent"},
    "joi": {"llm": "mock", "config": "comms-agent"},
    "data": {"llm": "mock", "config": "data-agent"},
    "eve": {"llm": "mock", "config": "qa-agent"},
    "quark": {"llm": "mock", "config": "finance-agent"},
    "og": {"llm": "mock", "config": "curator-agent"},
    "glyph": {"llm": "mock", "config": "creative-agent"},
    "hal": {"llm": "mock", "config": "audit-agent"}
}

# Version History
VERSION_HISTORY = {
    "max": [
        {"version": "0.1.0", "date": "2025-10-05", "llm": "llama3.1:8b", "notes": "Real agent with local LLM integration"},
        {"version": "0.2.0", "date": "2025-10-11", "llm": "llama3.1:8b", "notes": "Test coverage validation + WarmBoot run-055"},
        {"version": "0.3.0", "date": "2025-11-01", "llm": "llama3.1:8b", "notes": "Run-110: Added target_directory to task requirements, production-grade task orchestration"},
        {"version": "0.5.0", "date": "2025-11-05", "llm": "llama3.1:8b", "notes": "v0.5.0 memory integration - LanceDB semantic memory, task delegation memory recording, manifest workflow improvements"}
    ],
    "neo": [
        {"version": "0.1.0", "date": "2025-10-05", "llm": "qwen2.5:7b", "notes": "Real agent with file modification capabilities"},
        {"version": "0.2.0", "date": "2025-10-11", "llm": "qwen2.5:7b", "notes": "Test coverage validation + WarmBoot run-055"},
        {"version": "0.3.0", "date": "2025-11-01", "llm": "qwen2.5:7b", "notes": "Run-110: Fixed FileManager path combination, proper target_directory usage, production-grade file generation"},
        {"version": "0.5.0", "date": "2025-11-05", "llm": "qwen2.5:7b", "notes": "v0.5.0 memory integration - LanceDB semantic memory, build/deploy success memory recording, manifest-based workflow"}
    ]
}

def get_framework_version():
    """Get the current SquadOps framework version"""
    return SQUADOPS_VERSION

def get_agent_version(agent_name):
    """Get version for a specific agent"""
    return AGENT_VERSIONS.get(agent_name.lower(), "unknown")

def get_agent_config(agent_name):
    """Get configuration for a specific agent"""
    return CONFIG_VERSIONS.get(agent_name.lower(), {})

def update_agent_version(agent_name, version, llm=None, config=None, notes=""):
    """Update agent version and add to history"""
    agent_key = agent_name.lower()
    AGENT_VERSIONS[agent_key] = version
    
    if agent_key not in VERSION_HISTORY:
        VERSION_HISTORY[agent_key] = []
    
    VERSION_HISTORY[agent_key].append({
        "version": version,
        "date": "2025-10-05",  # Would use datetime.now().isoformat() in real implementation
        "llm": llm or CONFIG_VERSIONS.get(agent_key, {}).get("llm", "unknown"),
        "notes": notes
    })

def get_version_history(agent_name):
    """Get version history for a specific agent"""
    return VERSION_HISTORY.get(agent_name.lower(), [])

def rollback_agent(agent_name, target_version):
    """Rollback agent to a previous version"""
    agent_key = agent_name.lower()
    history = VERSION_HISTORY.get(agent_key, [])
    
    for entry in reversed(history):
        if entry["version"] == target_version:
            AGENT_VERSIONS[agent_key] = target_version
            return True
    return False

# Version increment rules:
# 0.1.X - Development phase (Task Management System)
# 0.2.X - Test Coverage & Quality milestone (90% coverage, guardrails)
# 0.3.X - Multi-agent expansion (full 10-agent squad)
# 0.4.X - Core SIPs implementation (Memory, Metrics, Tools)
# 0.5.X - Production deployment (enterprise features)
# 1.0.X - Stable release (external users + Backspring validation)

# Current status: 0.6.5 (Documentation updates: Docker build process, task adapter improvements, agent status updates)
# Previous: 0.1.4 (Task Management System complete)
# Next major: 0.3.0 (Multi-agent expansion with EVE, Nat, Data, HAL)