server {
  listen 80;
  server_name _;

  location /hello-squad/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /hello-squad/index.html;
  }
}
server {
  listen 80 default_server;
  server_name _;

  return 301 http://$host/hello-squad/;
}