server {
  listen 80;
  server_name _;

  location /hello-squad/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /hello-squad/index.html;
  }

  location / {
    return 301 /hello-squad/;
  }
}